USE lairLister_db;

INSERT INTO ad_statuses(name)
VALUES ('Active'),
       ('Sold'),
       ('Deleted');

INSERT INTO lair_types(name)
VALUE ('Domain');

INSERT INTO ad_locations(name)
VALUES ('High Forest'),
       ('Frozenfar'),
       ('Savage Frontier'),
       ('Silver Marches'),
       ('North Sword Coast'),
       ('Anauroch'),
       ('Dalelands'),
       ('Moonsea'),
       ('The Ride'),
       ('The Vast'),
       ('Damara'),
       ('Great Dale'),
       ('Impiltur'),
       ('Hordelands'),
       ('Narfell'),
       ('Rashermen'),
       ('Thesk'),
       ('Vaasa'),
       ('Evermeet'),
       ('Lantan'),
       ('Lands of Intrigue'),
       ('Moonshae Isles'),
       ('Nelanther Isles'),
       ('Nimbral'),
       ('Sword Coast'),
       ('Western Heartlands'),
       ('Trackless Sea'),
       ('Akanul'),
       ('Chondath'),
       ('Cormyr'),
       ('Dragon Coast'),
       ('Hlondeth'),
       ('Pirate Isles'),
       ('Sembia'),
       ('Sespech'),
       ('Turmish'),
       ('Shining Plains'),
       ('Aglarond'),
       ('Alturnbel'),
       ('Chessenta'),
       ('Chondalwood'),
       ('High Imaskar'),
       ('Mulhorand'),
       ('Murghorn'),
       ('Okoth'),
       ('Thay'),
       ('Tymanther'),
       ('Unther'),
       ('Chult'),
       ('Lapaliiya'),
       ('Samarach'),
       ('Tashalar'),
       ('Thindol'),
       ('Border Kingdoms'),
       ('Dambrath'),
       ('The Great Rift'),
       ('Halruaa'),
       ('Lake of Steam'),
       ('Shaar'),
       ('Durpar'),
       ('Estagund'),
       ('Var the Golden'),
       ('Luiren'),
       ('Ulgarth'),
       ('Utter East'),
       ('Veldorn'),
       ('Underdark');