USE lairLister_db;
INSERT INTO users (username, name, email, password, profile_image, bio)
VALUES ('DrMalicious', 'Dr. Malicious', 'dr.malicious@evil.com', 'M4d$C13n71$7', 'malicious.jpg', 'Greetings, puny mortals! I am Dr. Malicious, the mad scientist with a passion for chaos and destruction! With my army of loyal minions, I will bring the world to its knees!'),
       ('ProfChaos', 'Professor Chaos', 'prof.chaos@evil.com', 'iLOVEkittens!88', 'chaos.jpg', 'Ha ha ha! I am Professor Chaos, the brilliant-but-unstable scientist who loves nothing more than causing mayhem and destruction! With my latest invention, I will finally conquer the world!'),
       ('CrimsonCrusader', 'The Crimson Crusader', 'crimson.crusader@evil.com', 'ALLMUSTPERISH!!', 'crimson.jpg', 'I am the Crimson Crusader, sent by the heavens to rid the world of all sin and vice! With my trusty sword and unwavering faith, I will vanquish all considered evil in my path!'),
       ('ThePuppetmaster', 'The Puppetmaster', 'the.puppetmaster@evil.com', 'noStringsAttached...77', 'puppetmaster.jpg', 'Greetings, foolish humans. I am the Puppetmaster, the master of mind control! With a flick of my wrist, I can make anyone do my bidding. And soon, the world will be mine!'),
       ('DrDiabolical', 'Doctor Diabolical', 'dr.diabolical@evil.com', 'noPEEKING!', 'diabolical.jpg', 'Welcome to my lair, fools! I am Doctor Diabolical, the evil genius with a wicked sense of humor! With my army of robotic minions, I will conquer the world and make it my playground!'),
       ('ShadowQueen', 'The Shadow Queen', 'shadow.queen@evil.com', 'iAmTheNight!', 'shadow.jpg', 'Fear me, mortals! I am the Shadow King, the supernatural entity who feeds on your terror! With my power to manipulate reality, I will turn your worst nightmares into reality!'),
       ('BaronVonBloodlust', 'Baron Von Bloodlust', 'baron.v.bloodlust@evil.com', 'bloodIStasty66', 'bloodlust.jpg', 'I am Baron Von Bloodlust, the feared warlord with a bloodthirsty appetite for conquest and destruction! With my army of loyal soldiers, I will crush all who oppose me and rule the world with an iron fist!'),
       ('LadyDoom', 'Lady Doom', 'lady.doom@evil.com', 'doooooooooom', 'doom.jpg', 'Bow down before me, weaklings! I am Lady Doom, the sorceress with a thirst for power! With my dark magic and cunning, I will conquer all who stand in my way and make the world my domain!');